# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/protocolbuffers/txtpbfmt
%global goipath         github.com/protocolbuffers/txtpbfmt
%global commit          0e3c6a01a2113bb00ec28638cc1271484c44513a

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
Txtpbfmt parses, edits and formats text proto files in a way that preserves
comments.}

%global golicenses      LICENSE
%global godocs          docs README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Txtpbfmt parses, edits and formats text proto files in a way that preserves comments

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}
# FIXME builds fine on F38 w/o this one
BuildRequires:	golang(github.com/google/go-cmp/cmp)

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
