# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/crate-crypto/go-ipa
%global goipath         github.com/crate-crypto/go-ipa
%global commit          1643fdc2ead86e192b90d260da15d66d58bbbb60

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
# FIXME}

%global golicenses      LICENSE-APACHE LICENSE-MIT
%global godocs          readme.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        None

License:        MIT AND Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in bandersnatch/code_gen; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
# FIXME a very long running tests which fails after 10 minutes timeout
#%%gocheck
%endif

%files
%license LICENSE-APACHE LICENSE-MIT
%doc readme.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
