# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/holiman/goevmlab
%global goipath         github.com/holiman/goevmlab
%global commit          98c61355fce0544d69cff30d97c2610af9182628

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
Evm laboratory.}

%global golicenses      COPYING COPYING.LESSER
%global godocs          docs examples AUTHORS README.md binaries/README.md\\\
                        cmd/repro/README.md cmd/tracediff/README.md\\\
                        trophies/2022-11-30_besu_Dos/2022-11-30_besu_Dos.txt\\\
                        trophies/2022-11-30_besu_Dos/README.md\\\
                        trophies/2022-12-15-nimbus-\\\
                        eth1-consensus_err/README.md\\\
                        trophies/2022-12-24-nimbus-\\\
                        eth1-consensus_err/README.md\\\
                        trophies/2023-02-09_besu_consensus-err/README.md\\\
                        trophies/EIP-2929/README.md\\\
                        trophies/consensus_err/info.txt\\\
                        trophies/consensus_err/v2/info.txt

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Evm laboratory

License:        GPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in cmd/* ; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license COPYING COPYING.LESSER
%doc docs examples AUTHORS README.md binaries/README.md cmd/repro/README.md
%doc cmd/tracediff/README.md
%doc trophies/2022-11-30_besu_Dos/2022-11-30_besu_Dos.txt
%doc trophies/2022-11-30_besu_Dos/README.md
%doc trophies/2022-12-15-nimbus-eth1-consensus_err/README.md
%doc trophies/2022-12-24-nimbus-eth1-consensus_err/README.md
%doc trophies/2023-02-09_besu_consensus-err/README.md
%doc trophies/EIP-2929/README.md trophies/consensus_err/info.txt
%doc trophies/consensus_err/v2/info.txt
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
