# Generated by go2rpm 1.8.2
%bcond_without check

# https://github.com/bazelbuild/rules_go
%global goipath         github.com/bazelbuild/rules_go
Version:                0.38.1

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another pacage,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f

%global common_description %{expand:
Go rules for Bazel.}

%global golicenses      LICENSE.txt
%global godocs          docs examples AUTHORS CONTRIBUTING.md CONTRIBUTORS\\\
                        windows.rst README.rst go/core.rst go/crosstool.rst\\\
                        go/dependencies.rst go/extras.rst go/modes.rst\\\
                        go/providers.rst go/toolchains.rst go/nogo.rst\\\
                        go/private/skylib/README.rst go/tools/bazel/empty.txt\\\
                        go/tools/gazelle/README.rst proto/core.rst\\\
                        third_party/README.txt

Name:           %{goname}
Release:        %autorelease
Summary:        Go rules for Bazel

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in go/tools/windows-testrunner third_party go/tools/bazel_benchmark go/tools/releaser go/tools/gopackagesdriver go/tools/fetch_repo go/tools/builders; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE.txt
%doc docs examples AUTHORS CONTRIBUTING.md CONTRIBUTORS windows.rst README.rst
%doc go/core.rst go/crosstool.rst go/dependencies.rst go/extras.rst go/modes.rst
%doc go/providers.rst go/toolchains.rst go/nogo.rst go/private/skylib/README.rst
%doc go/tools/bazel/empty.txt go/tools/gazelle/README.rst proto/core.rst
%doc third_party/README.txt
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
