# Generated by go2rpm 1.8.2
%bcond_without check

# https://github.com/dgraph-io/ristretto
%global goipath         github.com/dgraph-io/ristretto
Version:                0.1.1

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another pacage,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f

%global common_description %{expand:
A high performance memory-bound Go cache.}

%global golicenses      LICENSE z/LICENSE
%global godocs          CHANGELOG.md README.md contrib/memtest/README.md\\\
                        z/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A high performance memory-bound Go cache

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in contrib/demo z/simd contrib/memtest; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE z/LICENSE
%doc CHANGELOG.md README.md contrib/memtest/README.md z/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
