# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/karalabe/usb
%global goipath         github.com/karalabe/usb
Version:                0.0.2

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
Self contained USB and HID library for Go.}

%global golicenses      LICENSE hidapi/LICENSE-bsd.txt hidapi/LICENSE-\\\
                        gpl3.txt hidapi/LICENSE-orig.txt hidapi/LICENSE.txt\\\
                        libusb/COPYING
%global godocs          AUTHORS README.md hidapi/AUTHORS.txt\\\
                        hidapi/README.txt libusb/AUTHORS

Name:           %{goname}
Release:        %autorelease
Summary:        Self contained USB and HID library for Go

License:        LGPL-2.1-only AND BSD-3-Clause AND GPL-3.0-only
URL:            %{gourl}
Source:         %{gosource}
Provides:	bundled(libusb)
Provides:	bundled(hidapi)

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/usb %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
# FIXME requires physical access to USB?
#%%gocheck
%endif

%files
%license LICENSE hidapi/LICENSE-bsd.txt hidapi/LICENSE-gpl3.txt
%license hidapi/LICENSE-orig.txt hidapi/LICENSE.txt libusb/COPYING
%doc AUTHORS README.md hidapi/AUTHORS.txt hidapi/README.txt libusb/AUTHORS
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
