# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/thomaso-mirodin/intmath
%global goipath         code.google.com/p/intmath
%global forgeurl        https://github.com/thomaso-mirodin/intmath
%global commit          5dc6d854e46e8db72326367254b8de5d2c5f2f4f

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another pacage,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f

%global goaltipaths github.com/thomaso-mirodin/intmath github.com/thomaso-mirodin/intmath/constants/c32 github.com/thomaso-mirodin/intmath/constants/c64

%global common_description %{expand:
Migration of an intmath library from from code.google.com/p/intmath.}

%global golicenses      LICENSE
%global godocs          README.md TODO

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Migration of an intmath library from from code.google.com/p/intmath

License:        BSD-3-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
