# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://gopkg.in/check.v1
%global goipath         gopkg.in/check.v1
%global forgeurl        https://github.com/go-check/check
%global commit          10cb98267c6cb43ea9cd6793f29ff4089c306974

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f

%global goaltipaths     github.com/go-check/check

%global common_description %{expand:
Rich testing for the Go language.}

%global golicenses      LICENSE
%global godocs          README.md TODO

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        Rich testing for the Go language

License:        BSD-2-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
