# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/multiformats/go-multihash
%global goipath         github.com/multiformats/go-multihash
Version:                0.2.1

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
Multihash implementation in Go.}

%global golicenses      LICENSE multihash/LICENSE
%global godocs          README.md multihash/README.md opts/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Multihash implementation in Go

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
for cmd in multihash; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE multihash/LICENSE
%doc README.md multihash/README.md opts/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
