# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/openconfig/reference
%global goipath         github.com/openconfig/reference
%global commit          5673235773d72bcbcf789584d69db98066c5303a

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another package,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f


%global common_description %{expand:
This repository contains reference implementations, specifications and tooling
related to OpenConfig-based network management.}

%global golicenses      LICENSE
%global godocs          README.md ietf/drafts/draft-ietf-idr-bgp-model-00.txt\\\
                        ietf/drafts/draft-ietf-idr-bgp-model-01.txt\\\
                        ietf/drafts/draft-ietf-idr-bgp-model-02.txt\\\
                        ietf/drafts/draft-ietf-rtgwg-policy-model-01.txt\\\
                        ietf/drafts/draft-openconfig-mpls-consolidated-\\\
                        model-00.txt ietf/drafts/draft-openconfig-mpls-\\\
                        consolidated-model-02.txt ietf/drafts/draft-\\\
                        openconfig-netmod-model-catalog-00.txt\\\
                        ietf/drafts/draft-openconfig-netmod-model-\\\
                        catalog-01.txt ietf/drafts/draft-openconfig-netmod-\\\
                        model-catalog-02.txt ietf/drafts/draft-openconfig-\\\
                        netmod-model-structure-00.txt ietf/drafts/draft-\\\
                        openconfig-netmod-opstate-00.txt ietf/drafts/draft-\\\
                        openconfig-netmod-opstate-01.txt ietf/drafts/draft-\\\
                        openconfig-rtgwg-gnmi-spec-00.txt ietf/drafts/draft-\\\
                        openconfig-rtgwg-gnmi-spec-01.txt ietf/drafts/draft-\\\
                        openconfig-rtgwg-local-routing-00.txt\\\
                        ietf/drafts/draft-openconfig-rtgwg-network-\\\
                        instance-00.txt ietf/drafts/draft-openconfig-rtgwg-\\\
                        network-instance-01.txt ietf/drafts/draft-shaikh-idr-\\\
                        bgp-model-00.txt ietf/drafts/draft-shaikh-idr-bgp-\\\
                        model-01.txt ietf/drafts/draft-shaikh-idr-bgp-\\\
                        model-02.txt ietf/drafts/draft-shaikh-rtgwg-policy-\\\
                        model-00.txt ietf/drafts/draft-shaikh-rtgwg-policy-\\\
                        model-01.txt rpc/gnmi/README.md\\\
                        rpc/gnmi/decimal64-deprecation.md rpc/gnmi/gnmi-\\\
                        authentication.md rpc/gnmi/gnmi-extensions.md\\\
                        rpc/gnmi/gnmi-history.md rpc/gnmi/gnmi-master-\\\
                        arbitration.md rpc/gnmi/gnmi-path-conventions.md\\\
                        rpc/gnmi/gnmi-path-strings.md rpc/gnmi/gnmi-\\\
                        specification.md rpc/gnmi/gnmignoissh-dialout-\\\
                        grpctunnel.md rpc/gnmi/mixed-schema.md\\\
                        rpc/gnmi/protobuf-vals.md rpc/gnoi/README.md

Name:           %{goname}
Version:        0
Release:        %autorelease -p
Summary:        This repository contains reference implementations, specifications and tooling related to OpenConfig-based network management

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
