# Generated by go2rpm 1.8.2
%bcond_without check
%global debug_package %{nil}

# https://github.com/libp2p/go-libp2p
%global goipath         github.com/libp2p/go-libp2p
Version:                0.25.1

# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
# ---
# New Fedora packages should use %%gometa -f, which makes the package
# ExclusiveArch to %%golang_arches_future and thus excludes the package from
# %%ix86. If the new package is needed as a dependency for another pacage,
# please consider removing that package from %%ix86 in the same way, instead of
# building more go packages for i686. If your package is not a leaf package,
# you'll need to coordinate the removal of the package's dependents first.
# ---
# REMOVE BEFORE SUBMITTING THIS FOR REVIEW
%gometa -f

%global common_description %{expand:
Libp2p implementation in Go.}

%global golicenses      LICENSE p2p/security/noise/LICENSE.md\\\
                        p2p/security/tls/LICENSE.md\\\
                        p2p/transport/websocket/LICENSE-APACHE\\\
                        p2p/transport/websocket/LICENSE-MIT
%global godocs          examples README.md ROADMAP.md docs p2p/host/resource-\\\
                        manager/README.md p2p/host/resource-\\\
                        manager/obs/grafana-dashboards/README.md\\\
                        p2p/net/README.md p2p/net/mock/log2.txt\\\
                        p2p/security/tls/cmd/README.md test-plans/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Libp2p implementation in Go

License:        Apache-2.0 AND MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
